server:
  port: 8070
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
---

server:
  port: 8070
spring:
  profiles: test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
  redis:
    host: 192.168.1.11
---

server:
  port: 8070
spring:
  profiles: prod
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
  redis:
    host: 192.168.1.11
