spring:
  profiles:
    active: dev

---
server:
  port: 8060
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.11:3306/etas_user?useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.1.11
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/user/**/*.xml
---
server:
  port: 8060
spring:
  profiles: prod
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.11:3306/etas_user?useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.1.11
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/user/**/*.xml
