server:
  port: 8095
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.11:3306/etas_fdfs?useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

fdfsHost: http://119.28.130.114  # http不能省
mybatis-plus:
  mapper-locations: classpath:mapper/**/*xml

