server:
  port: 8050
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/{segment}
          filters:
            - SetPath=/user/{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

